
export type TournamentStatus = 'active' | 'upcoming' | 'completed' | 'cancelled';
export type GameType = 'BGMI' | 'Free Fire' | 'Ludo King' | 'Other';
export type UserRank = 'Bronze' | 'Silver' | 'Gold' | 'Elite';

export interface VIPStatus {
  isActive: boolean;
  tier: 'none' | 'weekly' | 'monthly';
  expiryDate: string;
}

export interface UserProfile {
  id: string;
  email?: string;
  depositBalance: number;
  winningBalance: number;
  bonusBalance: number;
  referralCommissionBalance?: number;
  coins: number;
  walletBalanceINR: number; // Real-time INR Master Balance
  referralCode: string;
  referredBy?: string; // L1 Upline
  referredByL2?: string; // L2 Upline
  mlmLevel?: number; // 0, 1000, 3000, 5000, 10000
  vipLevel?: 'VIP 0' | 'VIP 1' | 'VIP 2'; // Tier System
  vipBonusEarned?: number;
  deviceId?: string; // Hardware Fingerprint
  lastIp?: string;
  country?: string;
  region?: string; // State/Region
  city?: string; // City Level Targeting
  preferredLanguage?: 'en' | 'or'; // English or Odia
  rank: UserRank;
  isAdmin?: boolean;
  isSuspended?: boolean; // Fraud Lock
  isVpnDetected?: boolean; // VPN Flag
  isEmulator?: boolean; // Emulator Flag
  adLoadFailCount?: number; // Ad-blocker tracker
  status?: 'active' | 'suspended';
  lastSpinTimestamp?: string;
  vipStatus?: VIPStatus;
  taskBalance?: number;
  weeklyWinnings?: number;
  totalReferrals?: number;
  videosWatchedToday?: number;
  lastVideoWatchDate?: string;
  isVpnActive?: boolean;
  isAccountActivated?: boolean;
  tasksCompletedCount?: number;
  networkTaskCompletions?: number; // Total tasks completed by all downlines
  totalNetworkRevenue?: number; // Total income generated by the network
  riskNoticeAccepted?: boolean; // Risk Disclosure Consent
  matchLossCount?: number; // Tracking losses for Pity Mechanism
  readingMinutes?: number; // Accumulated reading time
  weeklyPointsEarned?: number; // Tracking for weekly target
}

export interface SystemNotification {
  id: string;
  userId?: string;
  title: string;
  body: string;
  localizedBody?: string; // AI Generated regional text
  timestamp: string;
  type: 'broadcast' | 'payout' | 'mission' | 'system';
  imageUrl?: string;
  voucherCode?: string;
}

export interface UserLedgerEntry {
  id: string;
  userId?: string;
  type: 'deposit' | 'withdrawal' | 'income' | 'entry_fee' | 'referral' | 'conversion' | 'vip_purchase' | 'prediction_fee' | 'prediction_win' | 'video_reward' | 'shop_redemption' | 'cricket_stake' | 'esports_stake' | 'referral_comm' | 'mlm_joining' | 'vip_bonus' | 'game_fee' | 'multiplier_bet' | 'multiplier_win' | 'jackpot' | 'ludo_win' | 'ludo_fee' | 'reading_reward' | 'quiz_reward';
  amount: number;
  date: string;
  status: 'pending' | 'completed' | 'failed';
  description?: string;
  currencySymbol?: string;
  utrId?: string;
  isAutoVerified?: boolean;
  voucherCode?: string; // Digital code for shop redemptions
}

export interface PayoutRequest {
  id: string;
  userId: string;
  userEmail?: string;
  amount: number;
  fee: number;
  netAmount: number;
  method: string;
  destination: string;
  status: 'pending' | 'completed' | 'failed';
  timestamp: string;
  tasksCompleted?: number;
  isExpress?: boolean; // Fast Payout Signal
  isFlagged?: boolean; // Security Flag
}

export interface Movie {
  id: string;
  title: string;
  poster: string;
  videoUrl: string;
  category: string;
  createdAt: string;
}

export interface AppSettings {
  adminUpiId: string;
  maintenanceMode: boolean;
  automaticGatewayEnabled: boolean;
  conversionFeePercent: number;
}
