
export type TournamentStatus = 'active' | 'upcoming' | 'completed' | 'cancelled';
export type GameType = 'BGMI' | 'Free Fire' | 'Ludo King' | 'Other';
export type UserRank = 'Bronze' | 'Silver' | 'Gold' | 'Elite';

export interface VIPStatus {
  isActive: boolean;
  tier: 'none' | 'weekly' | 'monthly';
  expiryDate: string;
}

export interface UserProfile {
  id: string;
  email?: string;
  depositBalance: number;
  winningBalance: number;
  bonusBalance: number;
  referralCommissionBalance?: number;
  coins: number;
  referralCode: string;
  referredBy?: string; // L1 Upline
  referredByL2?: string; // L2 Upline
  mlmLevel?: number; // 0, 1000, 3000, 5000, 10000
  deviceId?: string; // Hardware Fingerprint
  lastIp?: string;
  country?: string;
  rank: UserRank;
  isAdmin?: boolean;
  isSuspended?: boolean; // Fraud Lock
  status?: 'active' | 'suspended';
  lastSpinTimestamp?: string;
  vipStatus?: VIPStatus;
  taskBalance?: number;
  weeklyWinnings?: number;
  totalReferrals?: number;
  videosWatchedToday?: number;
  lastVideoWatchDate?: string;
  isVpnActive?: boolean;
  isAccountActivated?: boolean;
  tasksCompletedCount?: number;
  networkTaskCompletions?: number; // Total tasks completed by all downlines
  totalNetworkRevenue?: number; // Total income generated by the network
  riskNoticeAccepted?: boolean; // Risk Disclosure Consent
}

export interface UserLedgerEntry {
  id: string;
  userId?: string;
  type: 'deposit' | 'withdrawal' | 'income' | 'entry_fee' | 'referral' | 'conversion' | 'vip_purchase' | 'prediction_fee' | 'prediction_win' | 'video_reward' | 'shop_redemption' | 'cricket_stake' | 'esports_stake' | 'referral_comm' | 'mlm_joining';
  amount: number;
  date: string;
  status: 'pending' | 'completed' | 'failed';
  description?: string;
  currencySymbol?: string;
  utrId?: string;
  isAutoVerified?: boolean;
  voucherCode?: string; // Digital code for shop redemptions
}

export interface AppSettings {
  maintenanceMode: boolean;
  offerWallEnabled: boolean;
  videoWallEnabled: boolean;
  referralRewardCoins: number;
  cpaLeadUrl: string;
  coinValuePerDollar: number;
  adminProfitPercentage: number;
  withdrawalFeePercent: number;
  conversionFeePercent: number;
  telegramUrl: string;
  heroBannerUrl?: string;
  cricketApiKey?: string;
  adminUpiId?: string;
  depositTelegramUrl?: string;
  automaticGatewayEnabled?: boolean;
  adMobAppId?: string;
  adMobBannerId?: string;
  adMobInterstitialId?: string;
  appLovinSdkKey?: string;
  appLovinZoneId?: string;
  earningBannerUrl?: string;
  earningBannerLink?: string;
  earningBannerReward?: number;
}

export interface Tournament {
  id: string;
  name: string;
  status: TournamentStatus;
  gameType: GameType;
  prizePool: string;
  entryFee: number;
  startDate: string;
  banner: string;
  streamUrl?: string;
  roomCredentials?: {
    roomId?: string;
    roomPassword?: string;
  };
}

export interface Registration {
  id: string;
  userId: string;
  tournamentId: string;
  gameId: string;
  joinedAt: string;
  feePaid: number;
}

export interface Match {
  id: string;
  tournamentId: string;
  teamA: { name: string; logo: string };
  teamB: { name: string; logo: string };
  scoreA: number;
  scoreB: number;
  status: 'live' | 'scheduled' | 'completed';
  description: string;
  votesA?: number;
  votesB?: number;
}

export interface PredictionPoll {
  id: string;
  question: string;
  optionA: string;
  optionB: string;
  entryFee: number;
  totalPool: number;
  category: string;
  expiry: string;
  timestamp: string;
}

export interface ESportsMatch {
  id: string;
  title: string;
  game: 'BGMI' | 'Free Fire' | 'Valorant';
  streamUrl?: string;
  status: 'live' | 'upcoming' | 'completed';
  timestamp: string;
}

export interface ESportsPoll {
  id: string;
  matchId: string;
  question: string;
  optionA: string;
  optionB: string;
  entryFee: number;
  totalPool: number;
  status: 'open' | 'closed';
}

export interface CricketMatch {
  id: string;
  teamA: string;
  teamB: string;
  teamALogo: string;
  teamBLogo: string;
  startTime: string;
  status: 'live' | 'upcoming' | 'completed';
  series: string;
  liveScore?: {
    runsA: string;
    runsB: string;
    overs: string;
    target?: string;
    lastBalls?: string[];
  };
  winner?: string;
}

export interface SystemNotification {
  id: string;
  title: string;
  body: string;
  imageUrl?: string;
  timestamp: string;
  type: 'broadcast' | 'payout' | 'mission';
  voucherCode?: string;
}

export interface SupportMessage {
  id: string;
  userId: string;
  message: string;
  aiResponse?: string;
  isFlagged?: boolean;
  status: 'open' | 'resolved';
  timestamp: string;
}

export interface ShopItem {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  category: string;
}
